apiVersion: v1
kind: Service
metadata:
  name: {{ include "device-controller.fullname" . }}
  namespace: {{ include "device-controller.namespace" . }}
  labels:
    {{- include "device-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "device-controller.controllerSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.controller.service.port }}
      targetPort: http
