apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: simulator
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    api_endpoint: {{ .Values.controller.apiEndpoint | quote }}
    mqtt_host: {{ .Values.controller.mqttHost | quote }}
    mqtt_port: {{ .Values.controller.mqttPort }}
    count: {{ .Values.simulator.count }}
    device_type: {{ .Values.simulator.deviceType | quote }}
    {{- with .Values.simulator.deviceTypes }}
    device_types:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    heartbeat_interval: {{ .Values.simulator.heartbeatInterval }}
    duration: {{ .Values.simulator.duration }}
    failure_rate: {{ .Values.simulator.failureRate }}
    ack_delay: {{ .Values.simulator.ackDelay }}
    churn_interval: {{ .Values.simulator.churnInterval }}
    churn_downtime: {{ .Values.simulator.churnDowntime }}
